cache:
  mount:
    - .git
    - /drone/docker

pipeline:
  build:
    image: ubuntu:14.04
    commands:
      - echo ${CI} 
  
  publish:
    registry.uphold.internal/drone-docker:
      registry: http://353893013802.dkr.ecr.us-east-1.amazonaws.com
      privileged: true
      repo: codebitsusers

  deploy:
    registry.uphold.internal/drone-rancher:
      privileged: true
      service: wallet/wallet
