cache:
  mount:
    - .git
    - /drone/docker

pipeline:
  build:
    image: ubuntu:14.04
    commands:
      - echo ${CI}  

  uphold/drone-docker:
    privileged: true
    params: eyAiRUNSX1NFQ1JFVF9LRVkiOiAiemFUZVF6OUtYRy9hY0t4ZEt1dnZwWjIzWkNmeW1iZnhIdWlDcXZNNCIsICJFQ1JfQUNDRVNTX0tFWSI6ICJBS0lBSUhDMkxDR05GQ0JUM0JMQSIgfQo=
