pipeline:
  build:
    image: ubuntu:14.04
    commands:
      - echo ${CI}  

  uphold/drone-docker:
    privileged: true
    params: eyAiRUNSX1NFQ1JFVF9LRVkiOiAiRk9PIiwgIkVDUl9BQ0NFU1NfS0VZIjogIkJBUiIgfQo=
