cache:
  mount:
    - .git
    - /drone/docker

pipeline:
  build:
    image: ubuntu:14.04
    commands:
      - echo ${CI} 
  
  publish:
      image: private.registry:5000/drone-ecr:0.5-rc1
      privileged: true


  deploy:
      image: private.registry:5000/drone-rancher:0.5-rc1
      privileged: true
      service: wallet/wallet
      rancher_services: service1,service2,service3
      