pipeline:
   # restore the cache from an sftp server
  sftp_cache:
    server: 172.17.0.15:22
    username: myuser
    password: mypassword
    restore: true
    mount: /done/node_modules

  build:
    image: ubuntu:14.04
    commands:
      - echo ${CI}
      - cp -R /drone/node_modules . || echo "Cache does not exist"
      - rm -rf /drone/node_modules
      - cat node_modules/test.txt || echo "Does not exist"
      - mkdir -p node_modules
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 > node_modules/test.txt
      - cat node_modules/test.txt
      - cp -R node_modules /drone
      - ls /drone

  sftp_cache:
    server: 172.17.0.15:22
    username: myuser
    password: mypassword
    rebuild: true
    mount: /drone/node_modules
