cache:
  mount:
    - .git
    - /drone/docker

pipeline:
  build:
    image: ubuntu:14.04
    commands:
      - echo ${CI}

  deploy:
      image: private.registry:5000/drone-rancher:0.5-rc1
      privileged: true
      rancher_services:
        - redis/redis
        - redis2/redis
