pipeline:
   # restore the cache from an sftp server
  sftp_cache:
    server: 172.17.0.15:22
    username: myuser
    password: mypassword
    restore: true
    mount: [ node_modules ]

  build:
    image: ubuntu:14.04
    commands:
      - echo ${CI}
      - cat node_modules/test.txt
      - mkdir node_modules
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 > node_modules/test.txt

  sftp_cache:
    server: 172.17.0.15:22
    username: myuser
    password: mypassword
    restore: true
    mount: [ node_modules ]
