workspace:
  path: /drone/src/github.com/mccricardo/codebitsusers
  base: /drone

pipeline:
   # restore the cache from an sftp server
  sftp_cache:
    image: plugins/sftp-cache
    restore: true
    mount:
      - node_modules

  build:
    image: ubuntu:14.04
    commands:
      - echo ${CI}
      - echo $GIT_ID_RSA
      - echo $PARAMS
      - cat node_modules/test.txt || echo "Does not exist"
      - mkdir -p node_modules
      - cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 > node_modules/test.txt
      - cat node_modules/test.txt

  #publish:
  #  image: registry.uphold.internal/drone-ecr
  #  privileged: true

  sftp_cache:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - node_modules
